name: Github Tag Workflow

on:
  push:
    branches:
      - main

jobs:
  github-tag:
    uses: pepsico-ecommerce/global_workflows_poc/.github/workflows/github-reusable-workflow-tag.yaml@v1.0.0
    secrets: inherit
